repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt ./...
        language: system
        types: [go]
        pass_filenames: false

      - id: go-imports
        name: goimports
        entry: sh -c 'go tool goimports -w .'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false

      - id: go-lint
        name: golangci-lint
        entry: sh -c 'make lint'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-test
        name: go test
        entry: go test -race ./...
        language: system
        types: [go]
        pass_filenames: false
